### ISSUE TITLE
Retrieving device serial number from Cisco switch

### ISSUE THREAD

**Issue by tiamdevops** [CiscoDevNet/python_code_samples_network#13]
I want my script to 1) login to a Cisco switch and do a "show inventory" command (done successfully so far) 2) save the output of "SN: FOCxxxxxxxx" _**in memory instead of saving it to a local file**_.

I want to do this in order to be able to match each serial number to a particular IP address.

Any ideas what I can do to achieve this?

Thanks!
Tiam

**Comment by xorrkaz** [comment]
I just added a script to this repo that does what you want with RESTCONF.  You could use that as a model for CLI commands if you wanted.  See the new RC-get-serial-numbers directory in this repo.

**Comment by tiamdevops** [comment]
@xorrkaz Thank you!!!!!

**Comment by tiamdevops** [comment]
I made a script that does that just in case anyone is interested. [You can find it here](https://github.com/tiamdevops/Handy-Python-Scripts/blob/master/Serial_Number_Getter).

**Comment by xorrkaz** [comment]
Not all Cisco serial numbers will start with FOC.  You might try this for your pattern:

regexoutput = re.search('SN:\s+(\w\d+)', output)
print(regexoutput.group(1))
