### ISSUE TITLE
NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by dgoodson12722** [CiscoDevNet/python_code_samples_network#5]
When executed from idle(python v 3.6.4)
========================= RESTART: /root/updateip.py =========================
The router has the following interfaces: 

  * GigabitEthernet1         
  * GigabitEthernet2         
  * GigabitEthernet3         
  * Loopback100              

Which Interface do you want to configure? GigabitEthernet2
Traceback (most recent call last):
  File "/root/updateip.py", line 181, in <module>
    sys.exit(main())
  File "/root/updateip.py", line 162, in main
    selected_interface = interface_selection(interfaces)
  File "/root/updateip.py", line 128, in interface_selection
    while sel == args.interface or not sel in [intf["name"] for intf in interfaces]:
NameError: name 'args' is not defined

or 

The router has the following interfaces: 

  * GigabitEthernet1         
  * GigabitEthernet2         
  * GigabitEthernet3         
  * Loopback100              

Which Interface do you want to configure? 2
Traceback (most recent call last):
  File "/root/updateip.py", line 181, in <module>
    sys.exit(main())
  File "/root/updateip.py", line 162, in main
    selected_interface = interface_selection(interfaces)
  File "/root/updateip.py", line 128, in interface_selection
    while sel == args.interface or not sel in [intf["name"] for intf in interfaces]:
NameError: name 'args' is not defined

**Comment by xorrkaz** [comment]
This appears to have been fixed already.  Thanks for reporting.
