### ISSUE TITLE
use of print statement

### ISSUE THREAD

**Issue by gregbo** [CiscoDevNet/python_code_samples_network#81]
To be compatible with newer Python versions, I suggest using the [print builtin function](https://docs.python.org/3/library/functions.html#print) instead.

**Comment by xorrkaz** [comment]
Most, if not all, of these samples were written for Python 2.7 where `print 'string'` was allowed.  If you want to submit a PR to futurize the modules, we'd appreciate it.

**Comment by xorrkaz** [comment]
Thanks for the PR!
