### ISSUE TITLE
updateip.py URL variables

### ISSUE THREAD

**Issue by gregbo** [CiscoDevNet/python_code_samples_network#83]
I tried to connect to ios-xe-mgmt.cisco.com at port 9443 with **nc** but got no response.  However, I was able to connect to port 443.  So, I sshed to ios-xe-mgmt.cisco.com and was able to verify that it was configured to accept https requests, at least.  This sandbox's configuration reminded me of another sandbox that I have recently used, sandbox-iosxe-recomm-1.cisco.com, which is actually a CNAME for it:

$ dig ios-xe-mgmt.cisco.com

; <<>> DiG 9.10.6 <<>> ios-xe-mgmt.cisco.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18601
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ios-xe-mgmt.cisco.com.		IN	A

;; ANSWER SECTION:
ios-xe-mgmt.cisco.com.	2252	IN	CNAME	sandbox-iosxe-recomm-1.cisco.com.
sandbox-iosxe-recomm-1.cisco.com. 2252 IN A	131.226.217.149

At the very least, the port needs to be changed from 9443 to 443.  But perhaps the script should be changed to allow the user to specify an alternate host, port, etc. in case those parameters need to be changed to access the sandbox associated with it.

**Comment by xorrkaz** [comment]
You've  had a good PR track record :-).  Feel like tackling this one, too?

**Comment by xorrkaz** [comment]
Thanks for your contributions!
